// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { Header } from "@/components/Home.index";
// import { FaFacebook, FaTwitter, FaInstagram, FaYoutube } from "react-icons/fa";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <Header/>
//         {children}
//         {/* <footer className="text-center p-6 bg-blue-600 text-white">
//       <p>&copy; 2025 SarkariReview. All rights reserved.</p>
//     </footer> */}

//     <footer className="bg-blue-900 text-white py-10 px-6 md:px-16">
//       <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-4 gap-8">
        
//         {/* Logo and Description */}
//         <div>
//           <h2 className="text-white text-2xl font-bold">SarkariReview</h2>
//           <p className="mt-2 text-gray-300">
//             Your trusted source for unbiased and in-depth product & service reviews.
//           </p>
//           <div className="flex space-x-4 mt-4">
//             <a href="#" className="text-gray-300 text-2xl hover:text-white">
//               <i className="fab fa-facebook"></i>
//             </a>
//             <a href="#" className="text-gray-300 text-2xl hover:text-white">
//               <i className="fab fa-twitter"></i>
//             </a>
//             <a href="#" className="text-gray-300 text-2xl hover:text-white">
//               <i className="fab fa-instagram"></i>
//             </a>
//             <a href="#" className="text-gray-300 text-2xl hover:text-white">
//               <i className="fab fa-youtube"></i>
//             </a>
//           </div>
//         </div>

//         {/* Quick Links */}
//         <div>
//           <h3 className="text-white text-lg font-semibold">Quick Links</h3>
//           <ul className="mt-2 space-y-2 text-gray-300">
//             <li><a href="#" className="hover:text-white">About Us</a></li>
//             <li><a href="#" className="hover:text-white">Terms & Conditions</a></li>
//             <li><a href="#" className="hover:text-white">Privacy Policy</a></li>
//             <li><a href="#" className="hover:text-white">Contact Us</a></li>
//           </ul>
//         </div>

//         {/* Popular Categories */}
//         <div>
//           <h3 className="text-white text-lg font-semibold">Popular Categories</h3>
//           <ul className="mt-2 space-y-2 text-gray-300">
//             <li><a href="#" className="hover:text-white">Tech Reviews</a></li>
//             <li><a href="#" className="hover:text-white">Gadgets</a></li>
//             <li><a href="#" className="hover:text-white">Software</a></li>
//             <li><a href="#" className="hover:text-white">Lifestyle</a></li>
//           </ul>
//         </div>

//         {/* Newsletter Subscription */}
//         <div>
//           <h3 className="text-white text-lg font-semibold">Stay Updated</h3>
//           <p className="text-gray-300 mt-2">
//             Subscribe for the latest reviews and updates.
//           </p>
//           <div className="flex mt-4">
//             <input
//               type="email"
//               placeholder="Your email"
//               className="bg-blue-800 text-gray-200 px-4 py-2 w-full rounded-l focus:outline-none"
//             />
//             <button className="bg-white text-blue-900 px-4 py-2 rounded-r hover:bg-gray-200">
//               Subscribe
//             </button>
//           </div>
//         </div>

//       </div>

//       {/* Copyright Section */}
//       <div className="text-center text-gray-300 text-sm mt-8 border-t border-gray-700 pt-4">
//         © 2025 SarkariReview. All rights reserved.
//       </div>
//     </footer>

   
//       </body>
//     </html>
//   );
// }




// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Home.index";
import { FaFacebook, FaTwitter, FaInstagram, FaYoutube } from "react-icons/fa";
import Providers from "../redux/Providers";  // ✅ Import Redux Provider

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <Providers>  {/* ✅ Wrap everything inside Redux Provider */}
          <Header />
          {children}

          {/* Footer */}
          <footer className="bg-blue-900 text-white py-10 px-6 md:px-16">
            <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-4 gap-8">
              {/* Logo and Description */}
              <div>
                <h2 className="text-white text-2xl font-bold">SarkariReview</h2>
                <p className="mt-2 text-gray-300">
                  Your trusted source for unbiased and in-depth product & service reviews.
                </p>
                <div className="flex space-x-4 mt-4">
                  <FaFacebook className="text-gray-300 text-2xl hover:text-white" />
                  <FaTwitter className="text-gray-300 text-2xl hover:text-white" />
                  <FaInstagram className="text-gray-300 text-2xl hover:text-white" />
                  <FaYoutube className="text-gray-300 text-2xl hover:text-white" />
                </div>
              </div>

              {/* Quick Links */}
              <div>
                <h3 className="text-white text-lg font-semibold">Quick Links</h3>
                <ul className="mt-2 space-y-2 text-gray-300">
                  <li><a href="#" className="hover:text-white">About Us</a></li>
                  <li><a href="#" className="hover:text-white">Terms & Conditions</a></li>
                  <li><a href="#" className="hover:text-white">Privacy Policy</a></li>
                  <li><a href="#" className="hover:text-white">Contact Us</a></li>
                </ul>
              </div>

              {/* Popular Categories */}
              <div>
                <h3 className="text-white text-lg font-semibold">Popular Categories</h3>
                <ul className="mt-2 space-y-2 text-gray-300">
                  <li><a href="#" className="hover:text-white">Tech Reviews</a></li>
                  <li><a href="#" className="hover:text-white">Gadgets</a></li>
                  <li><a href="#" className="hover:text-white">Software</a></li>
                  <li><a href="#" className="hover:text-white">Lifestyle</a></li>
                </ul>
              </div>

              {/* Newsletter Subscription */}
              <div>
                <h3 className="text-white text-lg font-semibold">Stay Updated</h3>
                <p className="text-gray-300 mt-2">
                  Subscribe for the latest reviews and updates.
                </p>
                <div className="flex mt-4">
                  <input
                    type="email"
                    placeholder="Your email"
                    className="bg-blue-800 text-gray-200 px-4 py-2 w-full rounded-l focus:outline-none"
                  />
                  <button className="bg-white text-blue-900 px-4 py-2 rounded-r hover:bg-gray-200">
                    Subscribe
                  </button>
                </div>
              </div>
            </div>

            {/* Copyright Section */}
            <div className="text-center text-gray-300 text-sm mt-8 border-t border-gray-700 pt-4">
              © 2025 SarkariReview. All rights reserved.
            </div>
          </footer>
        </Providers> {/* ✅ Redux Provider wrapped */}
      </body>
    </html>
  );
}
